// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTSCvSsyqOK-cILezqde3nc0kdha8d8o',
    appId: '1:795741385812:web:55674762336e9a918ae9c1',
    messagingSenderId: '795741385812',
    projectId: 'login-plantlink',
    authDomain: 'login-plantlink.firebaseapp.com',
    storageBucket: 'login-plantlink.appspot.com',
    measurementId: 'G-RKN8F2TCN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_tNuRzYZafK290u2wff9o1dSIeh2fW44',
    appId: '1:795741385812:android:8d1e25bf324e6e6f8ae9c1',
    messagingSenderId: '795741385812',
    projectId: 'login-plantlink',
    storageBucket: 'login-plantlink.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTzfAdhBuHbqV5yhdMvbjVbu5HiKPbmLA',
    appId: '1:795741385812:ios:3e2ce56aa638887b8ae9c1',
    messagingSenderId: '795741385812',
    projectId: 'login-plantlink',
    storageBucket: 'login-plantlink.appspot.com',
    iosClientId: '795741385812-7j9js0g7598ebpo724aikmlq94r1bdrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPlantlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTzfAdhBuHbqV5yhdMvbjVbu5HiKPbmLA',
    appId: '1:795741385812:ios:3bbfa5f63120b0698ae9c1',
    messagingSenderId: '795741385812',
    projectId: 'login-plantlink',
    storageBucket: 'login-plantlink.appspot.com',
    iosClientId: '795741385812-nuj9rs9csup4irha6c5mod0ar79eaac7.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPlantlink.RunnerTests',
  );
}
